### ISSUE TITLE
Code Review Week 14

### ISSUE THREAD

**Issue by LelinStam** [Sescheraun/WorldOfDarkness#11]
# Design/Code Review 3

#### Reviewer: Lisa Clemens

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Project Overview**|| |
||Which planned functionality has been met? |Security- login complete, Logging, Unit testing, full CRUD, Hibernate and amazing UI!!|
|| What planned functionality has not been met? | He still needs to consume a REST service and finish some of the website capabilities (ex- Player - crud own characters.) Also need to deploy to AWS|
||Describe the GitHub history and what it demonstrates about the project progress during the semester.| The project is updated fairly regularly throughout the semester with more capabilities.|
||Describe how peer and instructor feedback/recommendations were incorporated into the project.| In the beginning he incorporated the feedback well but it looks like he's fallen behind on using feedback to update project. |
||Other comments/notes?| Fairly complicated project with great UI but not meeting all planned capabilities. Maybe a little too ambitious?|
|**JSPs**|| |
||Evaluate the JSPs for templating, business logic, data validation, overall look and feel.| Templating is good & in place. Not much business logic or data validation on the actual JSPs- looks to be more in servlets. Adding validation to JSPs will help avoid if/else statements later. Overall look and feel is really cool!|
||Other comments/notes?| Amazing UI! Felt like a professional video game.|
|**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number) <li>single-purpose methods <li>well-structured project <li>descriptive naming of packages, classes, methods, variables <li>classes appropriately-sized  (no monster classes) <li> CPD (copy paste detection, meaning are the same lines of code repeated?) <li>are there candidates for super/subclass relationships, abstract classes, interfaces? <li>are any values hard-coded that should be in a properties file? <li>proper exception handling <li>proper error reporting to the user <li> code documentation | I think the project is well structured with descriptive naming conventions. I couldn't find any monster classes. They seemed to be primarily javabeans and CRUD for the Java Beans. I couldn't find and super/ subclass relationships or hard coded values. It seems like there could be more exceptions handling as the forms have some validation but could use more descriptive error messages for user. Maybe get a QA to test it. I really like the encrypted password you have set up! In addition, you may need more documentation.  |Other comments/notes?| |
|**Logging**|Evaluate the use of logging, for example:<li>appropriate use of logging statements in the code for error logging and debugging <li>logging levels used - info, debug, error <li> no occurrences of  System.out.printlns or printStackTrace() <li> logging works on AWS deploy|Yes, logging is extensively used and properly coded as debug vs info. I don't think it works on AWS yet since he hasn't deployed yet. There are a few system.print.outs: 3 in the test class in one in new user servlet. |Other comments/notes?| |
|**Unit Tests**|Evaluate the unit tests, for example: <li>tests are truly a unit test rather than a high level functional test <li>test data is appropriately cleaned up or handled <li> there is full coverage of methods that perform business logic or utility functions <li>redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After
| Yes, the unit tests are well done and look to be complete. They mostly deal with CRUD so have very good coverage without being functional tests. Test data is appropriately cleaned and handled. I couldn't find redundant code as @Before is in use. Not quite full coverage since he'll need to add a test for REST service.||Other comments/notes?| |
|**Security**|Evaluate authentication/authorization:| It is implemented and working (although he commented out during demo for code review). Looks to be in appropriate place and setup- with 3 roles: admin, gamemaster, and player. It is not working on AWS.|
||Is it implemented correctly and working locally as well as on AWS?
||Other comments/notes?| |
|**Web Service/API integration**|Evaluate the service/api integration, for example: <li> Which service/api is implemented? <li>How is  error handling of the service implemented? For example, what happens if the service is not available?| During his demo, REST service was not working but he said it usually is working. I think it is actually generating a rest service- not consuming one? Other than that, It looks good in his code and there is currently no error handling. |
||Other comments/notes?| |
|**Independent research topic**| What is the independent research topic?| Independent research topic was not covered or implemented.|
||Is the independent research topic/technique implemented in the project?| |
||Other comments/notes?| |
|**Deployment**| Has the application been successfully deployed to AWS?| No |
||Is the hosted application fully functioning?| No|
||Other comments/notes?| |

**Comment by pawaitemadisoncollege** [comment]
@LelinStam Nicely done. I know you are still working on the code quality report. Posting the output of the code quality tool here would be helpful (a screenshot will work).

**Comment by LelinStam** [comment]
Here are the results of the QA Plug. It only found about 11 errors, so not too bad.
<img width="821" alt="qaplugerror" src="https://user-images.githubusercontent.com/34919562/49889064-35c28700-fe06-11e8-817a-9c043196cb0b.PNG">
<img width="801" alt="qaplugerror2" src="https://user-images.githubusercontent.com/34919562/49889066-36f3b400-fe06-11e8-813e-e09d9d34f141.PNG">

**Comment by pawaitemadisoncollege** [comment]
Nothing found for the java source code?

**Comment by LelinStam** [comment]
Using the 'Find Bugs' plugin in addition to QA Plug- this is all I could find for java source code errors:
![image](https://user-images.githubusercontent.com/34919562/49889686-c51c6a00-fe07-11e8-8450-b85ad74d4a9a.png)

**Comment by Sescheraun** [comment]
I think I have all this fixed.  And how did you get those error displays?  I must have missed a step.
