### ISSUE TITLE
Instructor Feedback - Project Checkpoint 1

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Sescheraun/WorldOfDarkness#2]
- [x] Project plan - it's a-ok to use my plan as a model, however be sure to update it to make sense for your application.  Example: "Build the trail search jsp" probably doesn't make sense for your project.
- [x] .gitignor should be named .gitignore
- [x] Missing screen design for checkpoint 1.
- [x] You mentioned being stuck on the list of technologies. At minimum you should include the required technologies listed in the indie project details and rubric.

**Comment by Sescheraun** [comment]
Took care of item list one.
Um..  gitignor is named gitignor.
screen designs added

**Comment by pawaitemadisoncollege** [comment]
Doesn't it need to be .gitignor**e**? https://git-scm.com/docs/gitignore

**Comment by pawaitemadisoncollege** [comment]
Let me know when the screens have some detail to review, and I'll re-evaluate.

**Comment by Sescheraun** [comment]
Ok,  I refined the screen design images and pushed then,  I also added a technologies list to my readme and fixed the misspelling of .gitignore ... I can't believe I missed that.

**Comment by pawaitemadisoncollege** [comment]
Better!  
 I wonder if the Player screen should have list of characters at least to allow the player to view them? Same with the other two tabs that have a button a list of users on the admin, and a list of characters needing approval?

**Comment by Sescheraun** [comment]
My idea was that the users would listed for the admin to edit if desired, and the characters would be listed under the user that owned them

**Comment by pawaitemadisoncollege** [comment]
A picture might help me better ask my questions: 
<img width="1165" alt="markedupadminscreen" src="https://user-images.githubusercontent.com/13874466/46263735-51d9ac00-c4d8-11e8-90de-c2d4e7abc285.png">
