### ISSUE TITLE
Instructor Feedback - Week 4 Exercise

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Sescheraun/WorldOfDarkness#3]
- [x] If your instance variable name and column name are the same, you can skip the column annotation. . https://github.com/Sescheraun/WorldOfDarkness/blob/dd24337bf7623a37103a6ac83adb40d8890177a7/src/main/Java/sescheraun/WorldOfFutureDarkness/generator/User.java#L25-L29
- [x] Check project structure: src/main/Java should be src/main/java. I think you'll run into issue with maven if this is capitalized.
- [x] Missing some javadoc. Remember, there's a nice plugin that will generate these for you. Check out the week 1 follow-up videos for more details.
- [x] To be really thorough here, ideally compare all values on User. This can easily be done with a .equals() method on the User. There's a video demoing this in Week 5 Follow-up Videos. https://github.com/Sescheraun/WorldOfDarkness/blob/dd24337bf7623a37103a6ac83adb40d8890177a7/src/test/java/sescheraun/WorldOfFutureDarkness/persistance/UserDAOTest.java#L29

**Comment by Sescheraun** [comment]
The .equals methods are implemented.
