### ISSUE TITLE
Instructor Feedback - Project Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Sescheraun/WorldOfDarkness#7]
You have a good start here with your entities, daos, and unit tests.  

- [x] ERD? 
- [x] You have a good number of DAOs in your project - time to refactor to the generic dao.  You should leave all unit tests, just modify them to use the generic dao. Any new entities, should likewise be unit tested with regard to the hibernate/db "stuff".
- [x] Looks like there are just a couple System.out.println and printstacktrace statements to update to using log4j. https://github.com/Sescheraun/WorldOfDarkness/blob/1f0384597abd5b51e8595b7a20c4829e10e2a2fa/src/test/java/sescheraun/WorldOfFutureDarkness/test/util/Database.java#L44-L49
- [x] Package name should be lower case: "sescheraun.WorldOfFutureDarkness.persistance" should be "sescheraun.worldoffuturedarkness.persistence" or sescheraun.world_of_future_darkness.persistence;   A capital indicates a class. https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html
- [x] Are you regularly updating your time log and project plan? Looks like the last entry was 10/3?
- [x]  Remember to check off completed issue items using - [x], and then close the issue when all tasks are complete.

**Comment by Sescheraun** [comment]
Oh,  i knew something had gotten missed.  I will go back and bring the time log up to date.
